// Barrel de hooks del módulo de Descuentos y Cupones.
export { useDescuentos, fetchDescuentos } from './useDescuentos'
export { useCupones, fetchCupones } from './useCupones'
export { useDescuentosFiltros } from './useDescuentosFiltros'
export type { DescuentosTab } from './useDescuentosFiltros'
export { useToggleDescuento } from './useToggleDescuento'
export { useToggleCupon } from './useToggleCupon'
export { useEliminarDescuento } from './useEliminarDescuento'
export { useEliminarCupon } from './useEliminarCupon'
export { useDuplicarDescuento } from './useDuplicarDescuento'
export { useDuplicarCupon } from './useDuplicarCupon'
// Fase 3
export { useDescuento } from './useDescuento'
export { useCrearDescuento } from './useCrearDescuento'
export { useEditarDescuento } from './useEditarDescuento'
export { useCupon } from './useCupon'
export { useCrearCupon } from './useCrearCupon'
export { useEditarCupon } from './useEditarCupon'
// Fase 4 + 5
export { useAuditoria } from './useAuditoria'
export { useMetricas } from './useMetricas'
export { useMetricasDetalle } from './useMetricasDetalle'
