export { BadgeEstado } from './BadgeEstado'
export { BadgeTipo } from './BadgeTipo'
export { DescuentosFiltros } from './DescuentosFiltros'
export { DescuentosTabla } from './DescuentosTabla'
export { CuponesTabla } from './CuponesTabla'
// Fase 3 — Formularios
export { FormField, SectionCard, LabelRow } from './FormField'
export { ProductoArbol } from './ProductoArbol'
export { CategoriaLista } from './CategoriaLista'
export { TipoDescuentoSelector } from './TipoDescuentoSelector'
export { TipoCuponSelector } from './TipoCuponSelector'
export { AlcanceSelector } from './AlcanceSelector'
export { SelectorProductoOCategoria } from './SelectorProductoOCategoria'
export { BeneficioBonusSelector } from './BeneficioBonusSelector'
export { ConfigPorcentajeProducto } from './ConfigPorcentajeProducto'
export { ConfigMontoFijoProducto } from './ConfigMontoFijoProducto'
export { ConfigPorcentajeTicket } from './ConfigPorcentajeTicket'
export { ConfigMontoFijoTicket } from './ConfigMontoFijoTicket'
export { ConfigLlevaXPagaY } from './ConfigLlevaXPagaY'
export { ConfigCompraXObtieneZ } from './ConfigCompraXObtieneZ'
export { ConfigVolumen } from './ConfigVolumen'
export type { EscalaForm } from './ConfigVolumen'
export { VigenciaForm } from './VigenciaForm'
export { AplicacionSelector } from './AplicacionSelector'
export { PreviewPOS } from './PreviewPOS'
export { ResumenSidebar } from './ResumenSidebar'
export { PreviewCupon } from './PreviewCupon'
// Fase 4 — Detalle
export { DetalleEncabezado } from './DetalleEncabezado'
export { DetalleConfiguracion } from './DetalleConfiguracion'
export { DetalleProductos } from './DetalleProductos'
export { DetalleVigencia } from './DetalleVigencia'
export { HistorialCambios } from './HistorialCambios'
export { DetalleAcciones } from './DetalleAcciones'
export { DetalleRendimiento } from './DetalleRendimiento'
// Links compartibles
export { LinkCompartibleModal } from './LinkCompartibleModal'
export { LinkCompartibleSection } from './LinkCompartibleSection'
// Fase 5 — Métricas
export { MetricasKPIs } from './MetricasKPIs'
export { MetricasGrafico } from './MetricasGrafico'
export { MetricasFiltros } from './MetricasFiltros'
export { MetricasTabla } from './MetricasTabla'
export { MetricasDrawer } from './MetricasDrawer'
